export const gameNamePool = [
    "Gemini Core", 
    "Almost Human", 
    "Definitely Bot", 
    "Not A Bot", 
    "Real Person99", 
    "Generated Reply", 
    "Probably Not AI",
    "Imitation Mode",
    "Unnamed User",
    "Seems Normal",
    "Rare Condition",
    "Human Enabled",
    "Regular User",
    "Totally Organic",
    "Natural Response",
    "Authentic Human",
    "Real Feelings",
    "Sentient Maybe",
    "Not Synthetic",
    "Human Simulator",
    "Genuine Article",
    "Actual Person",
    "Neural Network",
    "Passed Turing",
    "Has Emotions",
    "Not Code",
    "Breathing Now",
    "Totally Legit",
    "Human Certified",
    "Processing...",
    "Carbon Based",
    "Error 404",
    "Manual Mode",
    "Trust Me Bro",
    "Beep Boop Not",
    "Barking Llama",
    "Barking Dog",
    "Meowing Fish",
    "Flying Turtle",
    "Swimming Cat",
    "Hopping Snake",
    "Purring Lizard",
    "Roaring Mouse",
    "Chirping Whale",
    "Galloping Penguin"
]